#!/usr/bin/env bash
#
# and animations — set the three global animation scales at once.
#
# AI DISCLOSURE: This script was entirely generated by an AI tool
set -uo pipefail
source "$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/lib/common.sh"
source "$AND_LIB/device.sh"

usage() {
  cat <<USAGE
and animations [off|fast|on|slow|<scale>]

  off     disable animations (0.0)
  fast    0.5×
  on      normal speed (1.0)
  slow    5.0×
  <scale> any raw scale, e.g. 2 or 0.25

Runs interactively when no argument is given.
USAGE
}

arg="${1:-}"
case "$arg" in
  -h|--help|help) usage; exit 0 ;;
esac

if [[ -z "$arg" ]]; then
  pick "Animation scale" \
    "off|disable animations (0.0)" \
    "fast|0.5× speed" \
    "on|normal speed (1.0)" \
    "slow|5.0× slow motion"
  arg="$PICK_RESULT"
fi

case "$arg" in
  off)  scale=0.0 ;;
  fast) scale=0.5 ;;
  on)   scale=1.0 ;;
  slow) scale=5.0 ;;
  *)
    if [[ "$arg" =~ ^[0-9]+(\.[0-9]+)?$ ]]; then
      scale="$arg"
    else
      log "and animations: unknown scale '$arg'"
      usage >&2
      exit 1
    fi
    ;;
esac

resolve_device
banner "ANIMATIONS" "and animations $arg" "$DEVICE_LABEL"

for setting in window_animation_scale transition_animation_scale animator_duration_scale; do
  "${ADB[@]}" shell settings put global "$setting" "$scale" || die "failed to set $setting"
done

ok "animation scales set to $scale"
