#!/usr/bin/env bash
#
# and current-activity — print the activity class that is on screen right now.
#
# AI DISCLOSURE: This script was entirely generated by an AI tool
set -uo pipefail
source "$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/lib/common.sh"
source "$AND_LIB/device.sh"

usage() {
  cat <<USAGE
and current-activity

Prints the fully-qualified class name of the foreground activity, along with
its package and the raw component. Reads \`dumpsys activity activities\` and
falls back to \`dumpsys window\` when the resumed activity is not reported
(e.g. while a dialog or the keyguard holds focus).
USAGE
}

case "${1:-}" in
  -h|--help|help) usage; exit 0 ;;
  "") ;;
  *) log "and current-activity: takes no arguments"; usage >&2; exit 1 ;;
esac

# Pulls the first `package/class` token out of a dumpsys line — the surrounding
# ActivityRecord{...}/Window{...} noise differs between Android versions but the
# component always looks the same.
component_from() {
  printf '%s' "$1" | tr -d '\r' | tr ' ' '\n' \
    | grep -m1 -E '^[A-Za-z0-9_.]+/[A-Za-z0-9_.$]+$'
}

resolve_device
banner "CURRENT ACTIVITY" "and current-activity" "$DEVICE_LABEL"

component=""
line="$("${ADB[@]}" shell dumpsys activity activities 2>/dev/null \
  | grep -m1 -iE 'mResumedActivity|topResumedActivity|^[[:space:]]*ResumedActivity:')"
[[ -n "$line" ]] && component="$(component_from "$line")"

if [[ -z "$component" ]]; then
  line="$("${ADB[@]}" shell dumpsys window 2>/dev/null \
    | grep -m1 -iE 'mCurrentFocus|mFocusedApp')"
  [[ -n "$line" ]] && component="$(component_from "$line")"
fi

[[ -z "$component" ]] && die "could not read the foreground activity. Is the screen on and unlocked?"

package="${component%%/*}"
class="${component#*/}"
# dumpsys abbreviates classes in the activity's own package to a leading dot.
[[ "$class" == .* ]] && class="$package$class"

ok "$class"
printf ' %sPackage%s   %s\n' "$DIM" "$RESET" "$package"
printf ' %sComponent%s %s\n' "$DIM" "$RESET" "$package/$class"
