#!/usr/bin/env bash
#
# and fix-date — sync an emulator's clock to the host clock.
#
# AI DISCLOSURE: This script was entirely generated by an AI tool
set -uo pipefail
source "$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/lib/common.sh"
source "$AND_LIB/device.sh"

usage() {
  cat <<USAGE
and fix-date

Sets the device clock to the host's current time. Needs a rootable image
(\`adb shell su root\`), so this works on emulators, not production devices.
USAGE
}

case "${1:-}" in
  -h|--help|help) usage; exit 0 ;;
  "") ;;
  *) log "and fix-date: takes no arguments"; usage >&2; exit 1 ;;
esac

resolve_device
banner "FIX DATE" "and fix-date" "$DEVICE_LABEL"

now="$(date +%m%d%H%M%Y.%S)"
if "${ADB[@]}" shell su root date "$now"; then
  ok "device clock set to $(date)"
else
  die "failed to set the clock. This needs a rootable image (su root)."
fi
