#!/usr/bin/env bash
#
# and font-size — set the system font scale.
#
# AI DISCLOSURE: This script was entirely generated by an AI tool
set -uo pipefail
source "$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/lib/common.sh"
source "$AND_LIB/device.sh"

usage() {
  cat <<USAGE
and font-size [0.85|1|1.15|1.30|<scale>]

  0.85    small
  1       default
  1.15    large
  1.30    largest
  <scale> any raw scale, e.g. 1.5

Runs interactively when no argument is given.
USAGE
}

arg="${1:-}"
case "$arg" in
  -h|--help|help) usage; exit 0 ;;
esac

if [[ -z "$arg" ]]; then
  pick "Font scale" \
    "0.85|small" \
    "1|default" \
    "1.15|large" \
    "1.30|largest"
  arg="$PICK_RESULT"
fi

if [[ "$arg" =~ ^[0-9]+(\.[0-9]+)?$ ]]; then
  # `1` and `1.` are valid input but Android wants a float.
  scale="$arg"
  [[ "$scale" == *.* ]] || scale="$scale.0"
else
  log "and font-size: unknown scale '$arg'"
  usage >&2
  exit 1
fi

resolve_device
banner "FONT SIZE" "and font-size $arg" "$DEVICE_LABEL"

"${ADB[@]}" shell settings put system font_scale "$scale" || die "failed to set font_scale"

ok "font scale set to $scale"
