#!/usr/bin/env bash
#
# and navigation — switch the system nav bar between gestures and three buttons.
#
# AI DISCLOSURE: This script was entirely generated by an AI tool
set -uo pipefail
source "$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/lib/common.sh"
source "$AND_LIB/device.sh"

usage() {
  cat <<USAGE
and navigation [gestures|buttons]

  gestures  gesture navigation
  buttons   three-button navigation

Runs interactively when no argument is given.
USAGE
}

arg="${1:-}"
case "$arg" in
  -h|--help|help) usage; exit 0 ;;
esac

if [[ -z "$arg" ]]; then
  pick "Navigation mode" \
    "gestures|swipe gesture navigation" \
    "buttons|classic three-button bar"
  arg="$PICK_RESULT"
fi

case "$arg" in
  gestures) overlay="com.android.internal.systemui.navbar.gestural" ;;
  buttons)  overlay="com.android.internal.systemui.navbar.threebutton" ;;
  *) log "and navigation: expected 'gestures' or 'buttons', got '$arg'"; usage >&2; exit 1 ;;
esac

resolve_device
banner "NAVIGATION" "and navigation $arg" "$DEVICE_LABEL"

"${ADB[@]}" shell cmd overlay enable-exclusive --category "$overlay" || die "failed to enable $overlay"

spinner 1 "Changing navigation mode…"

ok "navigation set to $arg"
