#!/usr/bin/env bash
#
# and paste — type the macOS clipboard into the focused field on the device.
#
# AI DISCLOSURE: This script was entirely generated by an AI tool
set -uo pipefail
source "$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/lib/common.sh"
source "$AND_LIB/device.sh"

usage() {
  cat <<USAGE
and paste

Sends the current macOS clipboard to the focused text field via
\`adb shell input text\`. Newlines are flattened to spaces — input text
cannot type a line break.
USAGE
}

case "${1:-}" in
  -h|--help|help) usage; exit 0 ;;
  "") ;;
  *) log "and paste: takes no arguments"; usage >&2; exit 1 ;;
esac

command -v pbpaste >/dev/null 2>&1 || die "pbpaste not found (macOS only)"

text="$(pbpaste)"
[[ -z "$text" ]] && die "clipboard is empty"

# `adb shell input text` runs the string through the device shell, so every
# character the shell would otherwise eat has to be escaped, and spaces become %s.
escape_for_input() {
  local s="$1"
  s="${s//$'\n'/ }"
  s="${s//$'\r'/ }"
  s="${s//\\/\\\\}"
  local ch
  for ch in '"' "'" '(' ')' '<' '>' '|' ';' '&' '*' '~' '`' '$' '#' '!'; do
    s="${s//"$ch"/\\$ch}"
  done
  s="${s// /%s}"
  printf '%s' "$s"
}

resolve_device
banner "PASTE" "and paste" "$DEVICE_LABEL"

"${ADB[@]}" shell input text "$(escape_for_input "$text")" || die "failed to send clipboard"

ok "sent ${#text} characters"
