#!/usr/bin/env bash
#
# and screenshot — capture a PNG from every connected device into ~/Downloads.
#
# Unlike the other commands this one deliberately targets all devices at once
# rather than resolving a single one.
# https://twitter.com/phileynick/status/1688922792887209985
#
# AI DISCLOSURE: This script was entirely generated by an AI tool
set -uo pipefail
source "$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/lib/common.sh"
source "$AND_LIB/device.sh"

usage() {
  cat <<USAGE
and screenshot [now|<seconds>]

  now        capture immediately
  <seconds>  count down that many seconds first, e.g. 5

Saves to ~/Downloads as "<device> - <timestamp>.png".
Runs interactively when no argument is given.
USAGE
}

arg="${1:-}"
case "$arg" in
  -h|--help|help) usage; exit 0 ;;
esac

if [[ -z "$arg" ]]; then
  pick "Screenshot" \
    "now|capture immediately" \
    "5|count down 5 seconds first"
  arg="$PICK_RESULT"
fi

if [[ "$arg" == "now" ]]; then
  delay=0
elif [[ "$arg" =~ ^[0-9]+$ ]]; then
  delay="$arg"
else
  log "and screenshot: expected 'now' or a number of seconds, got '$arg'"
  usage >&2
  exit 1
fi

require_adb
lines="$(adb_device_lines)"
[[ -z "$lines" ]] && die "no devices connected. Start an emulator or plug one in, then retry."

count="$(printf '%s\n' "$lines" | grep -c .)"
banner "SCREENSHOT" "and screenshot $arg" "all connected ($count)"

while [[ "$delay" -gt 0 ]]; do
  printf ' %sScreenshot in %s…%s\n' "$DIM" "$delay" "$RESET"
  sleep 1
  (( delay-- ))
done

failed=0
while IFS= read -r line; do
  [[ -z "$line" ]] && continue
  id="${line%% *}"
  name="$(device_label "$id" "$line")"
  # device_label appends "(id)" for physical devices; the filename wants the
  # bare model name.
  name="${name%% (*}"

  timestamp="$(date +"%Y-%m-%d at %H.%M.%S")"
  target="$HOME/Downloads/$name - $timestamp.png"

  if adb -s "$id" exec-out screencap -p > "$target"; then
    ok "$name → $target"
  else
    rm -f "$target"
    warn "failed to capture from $name"
    failed=1
  fi
done <<< "$lines"

exit "$failed"
