#!/usr/bin/env bash
#
# and talkback — turn the TalkBack screen reader on, off, or flip it.
#
# AI DISCLOSURE: This script was entirely generated by an AI tool
set -uo pipefail
source "$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/lib/common.sh"
source "$AND_LIB/device.sh"

TALKBACK_SERVICE="com.google.android.marvin.talkback/com.google.android.marvin.talkback.TalkBackService"

usage() {
  cat <<USAGE
and talkback [toggle|on|off]

  toggle  flip whatever state it is in now
  on      enable the TalkBack screen reader
  off     disable all accessibility services

Runs interactively when no argument is given.
USAGE
}

arg="${1:-}"
case "$arg" in
  -h|--help|help) usage; exit 0 ;;
esac

if [[ -z "$arg" ]]; then
  pick "TalkBack" \
    "toggle|flip the current state" \
    "on|enable the screen reader" \
    "off|disable accessibility services"
  arg="$PICK_RESULT"
fi

case "$arg" in
  toggle|on|off) ;;
  *) log "and talkback: expected 'toggle', 'on' or 'off', got '$arg'"; usage >&2; exit 1 ;;
esac

resolve_device
banner "TALKBACK" "and talkback $arg" "$DEVICE_LABEL"

action="$arg"
if [[ "$action" == "toggle" ]]; then
  current="$("${ADB[@]}" shell settings get secure enabled_accessibility_services 2>/dev/null | tr -d '\r\n')"
  if [[ -z "$current" || "$current" == "null" ]]; then
    action="on"
  else
    action="off"
  fi
fi

if [[ "$action" == "on" ]]; then
  "${ADB[@]}" shell settings put secure enabled_accessibility_services "$TALKBACK_SERVICE" \
    || die "failed to enable TalkBack"
else
  "${ADB[@]}" shell settings put secure enabled_accessibility_services null \
    || die "failed to disable TalkBack"
fi

ok "TalkBack turned $action"
