#!/usr/bin/env bash
#
# and talkback — turn the TalkBack screen reader on, off, or flip it.
#
# AI DISCLOSURE: This script was entirely generated by an AI tool
set -uo pipefail
source "$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/lib/common.sh"
source "$AND_LIB/device.sh"

TALKBACK_PACKAGE="com.google.android.marvin.talkback"
TALKBACK_SERVICE="$TALKBACK_PACKAGE/com.google.android.marvin.talkback.TalkBackService"

usage() {
  cat <<USAGE
and talkback [toggle|on|off]

  toggle  flip whatever state it is in now
  on      enable the TalkBack screen reader
  off     disable all accessibility services

Runs interactively when no argument is given.
USAGE
}

arg="${1:-}"
case "$arg" in
  -h|--help|help) usage; exit 0 ;;
esac

if [[ -z "$arg" ]]; then
  pick "TalkBack" \
    "toggle|flip the current state" \
    "on|enable the screen reader" \
    "off|disable accessibility services"
  arg="$PICK_RESULT"
fi

case "$arg" in
  toggle|on|off) ;;
  *) log "and talkback: expected 'toggle', 'on' or 'off', got '$arg'"; usage >&2; exit 1 ;;
esac

resolve_device
banner "TALKBACK" "and talkback $arg" "$DEVICE_LABEL"

action="$arg"
if [[ "$action" == "toggle" ]]; then
  current="$("${ADB[@]}" shell settings get secure enabled_accessibility_services 2>/dev/null | tr -d '\r\n')"
  if [[ "$current" == *"$TALKBACK_PACKAGE"* ]]; then
    action="off"
  else
    action="on"
  fi
fi

# TalkBack ships inside the Android Accessibility Suite, which is missing from
# AOSP and some Google APIs images. Without it the write below still succeeds and
# absolutely nothing happens, so stop rather than claim success. Only the
# enabling path cares: turning it off with nothing installed is already a no-op,
# and shoving the Play Store at someone trying to disable it would be perverse.
if [[ "$action" == "on" ]] && ! package_installed "$TALKBACK_PACKAGE"; then
  warn "TalkBack is not installed on $DEVICE_LABEL."
  if open_play_store "$TALKBACK_PACKAGE"; then
    die "Opened the Play Store listing — install Android Accessibility Suite, then rerun: and talkback $arg"
  fi
  die "No Play Store on this device either. Use a Play Store system image or a physical device."
fi

if [[ "$action" == "on" ]]; then
  "${ADB[@]}" shell settings put secure enabled_accessibility_services "$TALKBACK_SERVICE" \
    || die "failed to enable TalkBack"
else
  "${ADB[@]}" shell settings put secure enabled_accessibility_services null \
    || die "failed to disable TalkBack"
fi

ok "TalkBack turned $action"
