#!/usr/bin/env bash
#
# and touch-pointer — show or hide the on-screen touch indicators.
#
# AI DISCLOSURE: This script was entirely generated by an AI tool
set -uo pipefail
source "$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/lib/common.sh"
source "$AND_LIB/device.sh"

usage() {
  cat <<USAGE
and touch-pointer [on|off]

  on   draw a circle under every touch
  off  hide the touch indicators

Runs interactively when no argument is given.
USAGE
}

arg="${1:-}"
case "$arg" in
  -h|--help|help) usage; exit 0 ;;
esac

if [[ -z "$arg" ]]; then
  pick "Touch pointer" \
    "on|draw a circle under every touch" \
    "off|hide the touch indicators"
  arg="$PICK_RESULT"
fi

case "$arg" in
  on)  value=1 ;;
  off) value=0 ;;
  *) log "and touch-pointer: expected 'on' or 'off', got '$arg'"; usage >&2; exit 1 ;;
esac

resolve_device
banner "TOUCH POINTER" "and touch-pointer $arg" "$DEVICE_LABEL"

"${ADB[@]}" shell content insert --uri content://settings/system \
  --bind name:s:show_touches --bind value:i:"$value" || die "failed to set show_touches"

ok "touch pointer $arg"
