cask_args appdir: '/Applications'

tap 'homebrew/bundle'

brew 'curl'
brew 'git'
brew 'git-flow'
brew 'gradle'
brew 'jq'
brew 'nano'
brew 'python'
brew 'python3'
brew 'wget'

cask 'atom'
cask 'charles'
cask 'cyberduck'
cask 'firefox'
cask 'github-desktop'
cask 'gitkraken'
cask 'google-chrome'
cask 'plex-media-server'
cask 'sourcetree'
cask 'sublime-text'
cask 'slack'
cask 'transmission'
cask 'vlc'
cask 'zeplin'
