#!/usr/bin/env bash
#
# and: one entry point for the day-to-day adb chores — animation scales, font
# scale, screenshots, TalkBack and friends. Run it bare for an fzf menu, or
# pass the subcommand and its argument to skip every prompt.
#
# Each subcommand lives in its own script under commands/ and works standalone.
#
# AI DISCLOSURE: This script was entirely generated by an AI tool
set -uo pipefail
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/lib/common.sh"

COMMANDS=(
  "animations|window, transition and animator scales"
  "screenshot|capture every device to ~/Downloads"
  "touch-pointer|show or hide the touch indicators"
  "font-size|system font scale"
  "talkback|accessibility screen reader"
  "navigation|gesture or three-button nav bar"
  "paste|type the clipboard into the device"
  "current-activity|print the foreground activity class"
  "fix-date|sync the emulator clock to the host"
)

usage() {
  local entry name desc
  printf 'and — android adb helpers\n\n'
  printf 'Usage: and [command] [argument]\n\n'
  printf 'Commands:\n'
  for entry in "${COMMANDS[@]}"; do
    name="${entry%%|*}"
    desc="${entry#*|}"
    printf '  %-16s %s\n' "$name" "$desc"
  done
  cat <<'USAGE'

Run `and` with no arguments to pick interactively; every prompt prints the
equivalent one-liner so you can skip it next time. Run `and <command> --help`
for that command's arguments.

Examples:
  and screenshot now
  and screenshot 5
  and font-size 1.15
  and animations off
  and talkback toggle
  and current-activity
USAGE
}

# Maps the loose spellings worth supporting onto a script name under commands/.
canonical() {
  local raw
  raw="$(printf '%s' "$1" | tr '[:upper:]' '[:lower:]' | tr -d '_-')"
  case "$raw" in
    animations|animation|anim)            printf 'animations' ;;
    screenshot|screenshots|shot|ss)       printf 'screenshot' ;;
    touchpointer|touch|touches|pointer)   printf 'touch-pointer' ;;
    fontsize|font|fontscale)              printf 'font-size' ;;
    talkback|tb)                          printf 'talkback' ;;
    navigation|nav|navbar)                printf 'navigation' ;;
    paste|clipboard)                      printf 'paste' ;;
    currentactivity|activity|topactivity|currentfocus)
                                          printf 'current-activity' ;;
    fixdate|date|fixemulatordate)         printf 'fix-date' ;;
    *) return 1 ;;
  esac
}

if [[ $# -eq 0 ]]; then
  pick "Android" "${COMMANDS[@]}"
  exec "$AND_COMMANDS/$PICK_RESULT.sh"
fi

case "$1" in
  -h|--help|help) usage; exit 0 ;;
esac

if ! name="$(canonical "$1")"; then
  log "and: unknown command '$1'"
  usage >&2
  exit 1
fi
shift

exec "$AND_COMMANDS/$name.sh" "$@"
