#!/usr/bin/env bash
#
# papa: interactive helper to record/verify Paparazzi (JVM) screenshot tests
# without remembering the full gradle module path.
#
# AI DISCLOSURE: This script was entirely generated by an AI tool
set -uo pipefail

PRUNE_NAMES=(build .git .gradle .idea node_modules buildSrc gradle-plugins .kotlin out)

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD="$(tput bold)"; DIM="$(tput dim)"; RESET="$(tput sgr0)"
  CYAN="$(tput setaf 6)"; GREEN="$(tput setaf 2)"; RED="$(tput setaf 1)"
else
  BOLD=""; DIM=""; RESET=""; CYAN=""; GREEN=""; RED=""
fi

FZF_STYLE=(
  --height=~40% --layout=reverse --border=rounded --no-multi --info=hidden
  --pointer='❯' --prompt='› '
  --color='pointer:cyan:bold,label:cyan:bold,prompt:cyan:bold,header:dim,border:dim,fg+:bold,hl:cyan,hl+:cyan:bold'
)

log() { printf '%s\n' "$*" >&2; }
die() { log "papa: $*"; exit 1; }

hr() {
  local width
  width="$(tput cols 2>/dev/null)"; width=${width:-60}
  (( width > 80 )) && width=80
  printf '%*s' "$width" '' | tr ' ' '─'
}

command -v fzf >/dev/null 2>&1 || die "needs fzf. Install with: brew install fzf"
command -v git >/dev/null 2>&1 || die "needs git"

REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null)" || die "not inside a git repository"
cd "$REPO_ROOT" || exit 1

is_module_root() {
  [[ -f "$1/build.gradle" || -f "$1/build.gradle.kts" ]]
}

dir_to_gradle_path() {
  local dir="$1"
  printf ':%s\n' "${dir//\//:}"
}

gradle_path_to_dir() {
  local path="${1#:}"
  printf '%s\n' "${path//://}"
}

# Walk up from the directory containing $1 until a module root (build.gradle[.kts]) is found.
find_module_root_for_file() {
  local dir
  dir="$(dirname "$1")"
  while [[ "$dir" != "." && "$dir" != "/" && -n "$dir" ]]; do
    if is_module_root "$dir"; then
      printf '%s\n' "$dir"
      return 0
    fi
    dir="$(dirname "$dir")"
  done
  return 1
}

# Files changed but not committed (staged + unstaged + untracked).
uncommitted_files() {
  git status --porcelain 2>/dev/null | while IFS= read -r line; do
    line="${line:3}"
    case "$line" in
      *" -> "*) line="${line#*-> }" ;;
    esac
    printf '%s\n' "$line"
  done | grep -v '^$'
}

# Files touched by the last commit.
last_commit_files() {
  git show --name-only --pretty=format: HEAD 2>/dev/null | grep -v '^$'
}

# Prints unique module dirs reachable from a newline list of files.
roots_from_files() {
  local files="$1"
  local roots=""
  local f root
  while IFS= read -r f; do
    [[ -z "$f" ]] && continue
    if root="$(find_module_root_for_file "$f")"; then
      roots="$roots$root"$'\n'
    fi
  done <<< "$files"
  printf '%s' "$roots" | grep -v '^$' | sort -u
}

# Prints unique module directories guessed from changed files. Falls back to
# the last commit when uncommitted files exist but none map to a module
# (e.g. a stray file at the repo root).
guess_module_dirs() {
  local roots
  roots="$(roots_from_files "$(uncommitted_files)")"
  if [[ -z "$roots" ]]; then
    roots="$(roots_from_files "$(last_commit_files)")"
  fi
  printf '%s' "$roots"
}

# Finds module directories whose name matches $1 (case-insensitive substring),
# expanding one level down into submodules (e.g. app/, library/) when the
# matched directory itself isn't a module root.
search_module_dirs() {
  local term="$1"
  local prune_expr=()
  local name
  for name in "${PRUNE_NAMES[@]}"; do
    prune_expr+=(-name "$name" -o)
  done
  prune_expr=("${prune_expr[@]:0:${#prune_expr[@]}-1}")

  local matches
  matches="$(find . -maxdepth 6 \( "${prune_expr[@]}" \) -prune \
    -o -type d -iname "*${term}*" -print 2>/dev/null | sed 's#^\./##')"

  local results=""
  local d sub
  while IFS= read -r d; do
    [[ -z "$d" ]] && continue
    if is_module_root "$d"; then
      results="$results$d"$'\n'
    else
      for sub in "$d"/*/; do
        sub="${sub%/}"
        [[ -d "$sub" ]] || continue
        is_module_root "$sub" && results="$results$sub"$'\n'
      done
    fi
  done <<< "$matches"

  printf '%s' "$results" | grep -v '^$' | sort -u
}

# Interactive fzf pick from a newline list of module dirs, with an
# "Other (type manually)" entry always appended. Must be called directly
# (not via `$(...)`) so that `die` on cancel can actually exit the script
# instead of just the command-substitution subshell.
# Sets PICK_RESULT to the chosen dir, or "__OTHER__".
pick_module_dir() {
  local dirs="$1"
  local prompt="$2"
  local menu=""
  local d
  while IFS= read -r d; do
    [[ -z "$d" ]] && continue
    menu="$menu$(dir_to_gradle_path "$d")"$'\n'
  done <<< "$dirs"
  menu="$menu""Other (type manually)"

  local choice
  choice="$(printf '%s' "$menu" | grep -v '^$' | fzf "${FZF_STYLE[@]}" \
    --border-label=" $prompt " --header='↑↓ move · enter select · esc quit')"
  [[ -z "$choice" ]] && die "cancelled"

  if [[ "$choice" == "Other (type manually)" ]]; then
    PICK_RESULT="__OTHER__"
    return
  fi

  PICK_RESULT="$(gradle_path_to_dir "$choice")"
}

# Must be called directly (not via `$(...)`), same reasoning as pick_module_dir.
# Sets RESOLVED_MODULE_DIR.
resolve_module() {
  local candidates
  candidates="$(guess_module_dirs)"

  if [[ -z "$candidates" ]]; then
    log "papa: couldn't guess a module from uncommitted changes or the last commit."
  fi

  while true; do
    if [[ -n "$candidates" ]]; then
      pick_module_dir "$candidates" "Run paparazzi in module"
    else
      PICK_RESULT="__OTHER__"
    fi

    if [[ "$PICK_RESULT" != "__OTHER__" ]]; then
      RESOLVED_MODULE_DIR="$PICK_RESULT"
      return 0
    fi

    local term
    read -rp "Module name: " term || die "cancelled"
    [[ -z "$term" ]] && { log "papa: empty module name, try again."; candidates=""; continue; }

    candidates="$(search_module_dirs "$term")"
    if [[ -z "$candidates" ]]; then
      log "papa: no module found matching '$term'. Try again."
    fi
  done
}

# Must be called directly (not via `$(...)`), same reasoning as pick_module_dir.
# Sets PICKED_ACTION.
pick_action() {
  local choice
  choice="$(printf 'Record\nVerify\n' | fzf "${FZF_STYLE[@]}" \
    --border-label=" Record or verify? " --header='↑↓ move · enter select · esc quit')"
  [[ -z "$choice" ]] && die "cancelled"
  PICKED_ACTION="$choice"
}

main() {
  local gradle_path task cmd title status elapsed
  resolve_module
  gradle_path="$(dir_to_gradle_path "$RESOLVED_MODULE_DIR")"

  pick_action
  case "$PICKED_ACTION" in
    Record) task="recordJvmScreenshots"; title="RECORD" ;;
    Verify) task="verifyJvmScreenshots"; title="VERIFY" ;;
    *) die "unknown action: $PICKED_ACTION" ;;
  esac

  cmd="./gradlew ${gradle_path}:${task}"

  printf '\n%s%s%s\n' "$CYAN" "$(hr)" "$RESET"
  printf ' %s%sPAPARAZZI · %s%s\n' "$BOLD" "$CYAN" "$title" "$RESET"
  printf ' %sModule%s   %s\n' "$DIM" "$RESET" "$gradle_path"
  printf ' %sCommand%s  %s\n' "$DIM" "$RESET" "$cmd"
  printf '%s%s%s\n\n' "$CYAN" "$(hr)" "$RESET"

  SECONDS=0
  eval "$cmd"
  status=$?
  elapsed=$SECONDS

  printf '\n'
  if [[ $status -eq 0 ]]; then
    printf '%s%s%s\n' "$GREEN" "$(hr)" "$RESET"
    printf ' %s%s✓ %s PASSED%s  %s(%ss)%s\n' "$BOLD" "$GREEN" "$title" "$RESET" "$DIM" "$elapsed" "$RESET"
    [[ "$title" == "RECORD" ]] && printf ' %sBaselines written under src/test/snapshots/images/ — commit them.%s\n' "$DIM" "$RESET"
    printf '%s%s%s\n' "$GREEN" "$(hr)" "$RESET"
  else
    printf '%s%s%s\n' "$RED" "$(hr)" "$RESET"
    printf ' %s%s✗ %s FAILED%s  %s(%ss)%s\n' "$BOLD" "$RED" "$title" "$RESET" "$DIM" "$elapsed" "$RESET"
    printf ' %sDiff images: %s/build/paparazzi/failures/%s\n' "$DIM" "${RESOLVED_MODULE_DIR}" "$RESET"
    printf '%s%s%s\n' "$RED" "$(hr)" "$RESET"
  fi

  exit "$status"
}

main "$@"
