#!/usr/bin/env bash
#
# Shared UI helpers for the `and` CLI: colours, fzf styling, pickers and banners.
# Sourced by and.sh and by every script under commands/.
#
# AI DISCLOSURE: This script was entirely generated by an AI tool

[[ -n "${AND_COMMON_LOADED:-}" ]] && return 0
AND_COMMON_LOADED=1

AND_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
AND_LIB="$AND_ROOT/lib"
AND_COMMANDS="$AND_ROOT/commands"

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD="$(tput bold)"; DIM="$(tput dim)"; RESET="$(tput sgr0)"
  CYAN="$(tput setaf 6)"; GREEN="$(tput setaf 2)"; RED="$(tput setaf 1)"
else
  BOLD=""; DIM=""; RESET=""; CYAN=""; GREEN=""; RED=""
fi

# fzf 0.35 introduced --border-label, the adaptive `--height=~N%` prefix, and
# named/attributed colour specs. Older builds (0.24 still ships on machines that
# installed fzf years ago) reject all three with a hard parse error, so pick the
# style that matches whatever fzf is actually installed. The legacy branch folds
# the border label into --header and spells colours as ANSI numbers.
FZF_MODERN=0
if command -v fzf >/dev/null 2>&1; then
  _fzf_version="$(fzf --version 2>/dev/null | awk '{print $1}')"
  IFS=. read -r _fzf_major _fzf_minor _ <<< "$_fzf_version"
  if [[ "${_fzf_major:-}" =~ ^[0-9]+$ && "${_fzf_minor:-}" =~ ^[0-9]+$ ]] \
     && { (( _fzf_major > 0 )) || (( _fzf_minor >= 35 )); }; then
    FZF_MODERN=1
  fi
  unset _fzf_version _fzf_major _fzf_minor
fi

if [[ "$FZF_MODERN" -eq 1 ]]; then
  FZF_STYLE=(
    --height=~40% --layout=reverse --border=rounded --no-multi --info=hidden --ansi
    --pointer='❯' --prompt='› '
    --color='pointer:cyan:bold,label:cyan:bold,prompt:cyan:bold,header:dim,border:dim,fg+:bold,hl:cyan,hl+:cyan:bold'
  )
else
  FZF_STYLE=(
    --height=40% --layout=reverse --border=rounded --no-multi --info=hidden --ansi
    --pointer='❯' --prompt='› '
    --color='pointer:6,prompt:6,header:8,border:8,fg+:bold,hl:6,hl+:6'
  )
fi

log() { printf '%s\n' "$*" >&2; }
die() { printf '%sand:%s %s\n' "$RED" "$RESET" "$*" >&2; exit 1; }

hr() {
  local width
  width="$(tput cols 2>/dev/null)"; width=${width:-60}
  (( width > 80 )) && width=80
  printf '%*s' "$width" '' | tr ' ' '─'
}

require_fzf() {
  command -v fzf >/dev/null 2>&1 || die "needs fzf. Install with: brew install fzf"
}

# pick "Border label" "value|description" "value|description" ...
#
# Renders an fzf menu and sets PICK_RESULT to the chosen value. Must be called
# directly (not via `$(...)`) so that `die` on cancel exits the script rather
# than just a command-substitution subshell.
#
# Descriptions are documentation, not search keys: --nth=1 restricts matching to
# the value so that e.g. "screen" finds screenshot without also dragging in
# talkback for "accessibility screen reader".
pick() {
  local label="$1"; shift
  require_fzf

  local entry value desc padded width=0
  for entry in "$@"; do
    value="${entry%%|*}"
    (( ${#value} > width )) && width=${#value}
  done

  local menu=""
  for entry in "$@"; do
    value="${entry%%|*}"
    desc="${entry#*|}"
    if [[ "$desc" == "$entry" ]]; then
      menu+="$value"$'\n'
    else
      printf -v padded '%-*s' "$width" "$value"
      menu+="$padded  $DIM$desc$RESET"$'\n'
    fi
  done

  local args=("${FZF_STYLE[@]}" --nth=1)
  if [[ "$FZF_MODERN" -eq 1 ]]; then
    args+=(--border-label=" $label " --header='↑↓ move · enter select · esc quit')
  else
    args+=(--header="$label · ↑↓ move · enter select · esc quit")
  fi

  local choice
  choice="$(printf '%s' "$menu" | grep -v '^[[:space:]]*$' | fzf "${args[@]}")"
  [[ -z "$choice" ]] && die "cancelled"
  PICK_RESULT="${choice%% *}"
}

# banner "TITLE" "and <full command>" [device label]
#
# Printed before every action so the non-interactive form of what just got
# picked is always visible to copy.
banner() {
  local title="$1" cmd="$2" device="${3:-}"
    # Hand the resolved command back to the zsh wrapper (see aliases.zsh)
  [[ -n "${AND_RESOLVED_FILE:-}" ]] && printf '%s\n' "$cmd" > "$AND_RESOLVED_FILE"
  printf '\n%s%s%s\n' "$CYAN" "$(hr)" "$RESET"
  printf ' %s%sANDROID · %s%s\n' "$BOLD" "$CYAN" "$title" "$RESET"
  [[ -n "$device" ]] && printf ' %sDevice%s   %s\n' "$DIM" "$RESET" "$device"
  printf ' %sCommand%s  %s\n' "$DIM" "$RESET" "$cmd"
  printf '%s%s%s\n\n' "$CYAN" "$(hr)" "$RESET"
}

ok()   { printf ' %s%s✓%s %s\n' "$BOLD" "$GREEN" "$RESET" "$*"; }
warn() { printf ' %s!%s %s\n' "$RED" "$RESET" "$*" >&2; }

# _spin_frame <tick> <text>
#
# Redraws the spinner line in place. Shared by spinner and countdown.
_spin_frame() {
  local tick="$1" text="$2"
  local frames=(⠋ ⠙ ⠹ ⠸ ⠼ ⠴ ⠦ ⠧ ⠇ ⠏)
  printf '\r %s%s%s %s%s%s' "$CYAN" "${frames[tick % 10]}" "$RESET" "$DIM" "$text" "$RESET"
}

# spinner <seconds> <message>
#
# Holds a braille spinner for roughly <seconds> then erases the line, to cover
# the gap between an adb command returning and the device actually settling.
# The wait is cosmetic, so a non-terminal stdout gets one dim line and no delay.
spinner() {
  local seconds="$1" message="$2"
  local ticks=$(( seconds * 10 )) i

  if [[ ! -t 1 ]]; then
    printf ' %s%s%s\n' "$DIM" "$message" "$RESET"
    return
  fi

  for (( i = 0; i < ticks; i++ )); do
    _spin_frame "$i" "$message"
    sleep 0.1
  done
  printf '\r\033[K'
}

# countdown <seconds> <prefix>
#
# Spinner whose message counts the remaining seconds down, e.g.
# "Screenshot in 5…". Unlike spinner the delay is the point rather than
# decoration, so a non-terminal stdout still waits, printing a line per second.
countdown() {
  local seconds="$1" prefix="$2"
  local ticks=$(( seconds * 10 )) i remaining

  if [[ ! -t 1 ]]; then
    for (( remaining = seconds; remaining > 0; remaining-- )); do
      printf ' %s%s %s…%s\n' "$DIM" "$prefix" "$remaining" "$RESET"
      sleep 1
    done
    return
  fi

  for (( i = 0; i < ticks; i++ )); do
    remaining=$(( seconds - i / 10 ))
    _spin_frame "$i" "$prefix ${remaining}…"
    sleep 0.1
  done
  printf '\r\033[K'
}
