#!/usr/bin/env bash
#
# Device resolution for the `and` CLI.
#
# Most adb settings commands fail outright when more than one device is
# attached, so every command that targets a single device calls resolve_device
# first: zero devices is an error, one is used silently, and two or more get an
# fzf picker. Afterwards "${ADB[@]}" is an adb invocation pinned to that device.
#
# AI DISCLOSURE: This script was entirely generated by an AI tool

[[ -n "${AND_DEVICE_LOADED:-}" ]] && return 0
AND_DEVICE_LOADED=1

require_adb() {
  command -v adb >/dev/null 2>&1 || \
    die "adb not found in PATH. Expected it under \$ANDROID_HOME/platform-tools."
}

# Lines from `adb devices -l` for devices in the "device" state, i.e. skipping
# the header, blank lines, and anything offline or unauthorized.
adb_device_lines() {
  adb devices -l 2>/dev/null | tail -n +2 | awk 'NF >= 2 && $2 == "device"'
}

# device_label <id> <full `adb devices -l` line>
device_label() {
  local id="$1" line="$2" model
  if [[ "$id" == emulator-* ]]; then
    printf '%s' "$id"
    return
  fi
  model="$(printf '%s' "$line" | tr ' ' '\n' | sed -n 's/^model://p' | head -1)"
  if [[ -n "$model" ]]; then
    printf '%s (%s)' "$model" "$id"
  else
    printf '%s' "$id"
  fi
}

# Sets ADB (array), DEVICE_ID and DEVICE_LABEL. Must be called directly (not via
# `$(...)`) so that `die` and the fzf picker behave.
resolve_device() {
  require_adb

  local lines count=0
  lines="$(adb_device_lines)"
  [[ -n "$lines" ]] && count="$(printf '%s\n' "$lines" | grep -c .)"

  if [[ "$count" -eq 0 ]]; then
    die "no devices connected. Start an emulator or plug one in, then retry."
  fi

  local id line
  if [[ "$count" -eq 1 ]]; then
    line="$lines"
    id="${line%% *}"
  else
    local entries=() l i
    while IFS= read -r l; do
      [[ -z "$l" ]] && continue
      i="${l%% *}"
      entries+=("$i|$(device_label "$i" "$l")")
    done <<< "$lines"

    pick "Target device" "${entries[@]}"
    id="$PICK_RESULT"
    line="$(printf '%s\n' "$lines" | grep "^$id ")"
  fi

  DEVICE_ID="$id"
  DEVICE_LABEL="$(device_label "$id" "$line")"
  ADB=(adb -s "$id")
}

PLAY_STORE_PACKAGE="com.android.vending"

# package_installed <package>
#
# True when the resolved device has exactly <package> installed. `pm list
# packages` filters by substring, so the match is anchored to avoid
# com.foo.bar answering for com.foo.
package_installed() {
  "${ADB[@]}" shell pm list packages "$1" 2>/dev/null \
    | tr -d '\r' | grep -qx "package:$1"
}

# open_play_store <package>
#
# Opens the Play Store listing for <package> on the resolved device. Returns
# non-zero when the device has no Play Store, so callers can fall back to a
# plain error instead of promising an install route that does not exist.
open_play_store() {
  local package="$1" out
  package_installed "$PLAY_STORE_PACKAGE" || return 1
  out="$("${ADB[@]}" shell am start -a android.intent.action.VIEW \
    -d "market://details?id=$package" 2>&1 | tr -d '\r')"
  # `am start` exits 0 even when it fails to resolve the intent.
  [[ "$out" != *Error* ]]
}
